Update verbiage and readme

diff --git a/bin/rbenv-download b/bin/rbenv-download
--- a/bin/rbenv-download
+++ b/bin/rbenv-download
@@ -26,11 +26,11 @@ ruby_version=$1
 package_url="${BINARIES_BASE}/${SYSTEM_NAME}/${SYSTEM_VERSION}/${SYSTEM_ARCH}/ruby-${ruby_version}.tar.gz"
 package_url=`echo $package_url | awk '{print tolower($0)}'`
 
-echo "Download and extract ruby ${ruby_version} from the RVM repository"
+echo "Download and extract ruby ${ruby_version} from ${BINARIES_BASE}"
 
 if ! check_url $package_url; then
   echo "${url} cannot be reached" >&2
-  echo "Cannot find a built version of ruby '${ruby_version}' compiled for your current system: ${SYSTEM_NAME} ${SYSTEM_ARCH} (${SYSTEM_VERSION})" >&2
+  echo "Could not find a pre-compiled version of ruby '${ruby_version}' for your current system: ${SYSTEM_NAME} ${SYSTEM_ARCH} (${SYSTEM_VERSION})" >&2
   exit 1
 fi
 
